import {
  Coffee, Utensils, Layers, ClipboardList, Monitor,
  Calendar, BookOpen, Bell, ShoppingBag, MapPin,
  CreditCard, Navigation2, User, Lock, ShieldCheck,
  RefreshCw, Heart, Copy, Palette, Tag, Share2,
  Users, LayoutDashboard, ChefHat, Tablet, Eye,
  ClipboardCheck, Star, Clock, FileText, UserCheck,
  Package, Database, Warehouse, Truck, BarChart3,
  TrendingUp, MessageSquare, ScrollText, Archive,
  Banknote, Receipt, Building2, Settings, Mail,
  PlayCircle, QrCode, Smartphone, Globe, Gift,
  Zap, PieChart, LineChart, AlertTriangle, BoxSelect,
  ChevronRight, Boxes, FlaskConical, Layers2, Wrench,
  BadgeCheck,
} from "lucide-react";

export interface CafePageEntry {
  path: string;
  titleAr: string;
  descAr: string;
  icon: any;
  badge: string;
  badgeColor: string;
  theme: "orange" | "dark" | "green" | "violet" | "sky" | "red" | "slate";
}

export interface CafeSection {
  id: string;
  titleAr: string;
  emoji: string;
  color: string;
  pages: CafePageEntry[];
}

export const CAFE_SECTIONS: CafeSection[] = [
  // ══════════════════════════════════════════════
  // 1. صفحات العملاء العامة
  // ══════════════════════════════════════════════
  {
    id: "customer-public",
    titleAr: "بوابة العملاء — صفحات عامة (بدون تسجيل دخول)",
    emoji: "☕",
    color: "#b45309",
    pages: [
      {
        path: "/welcome",
        titleAr: "صفحة الترحيب الرئيسية",
        descAr: "أول صفحة يراها العميل عند فتح تطبيق الكافيه — تعرض الشعار وصورة رئيسية جذابة وزر «ابدأ الطلب» للانتقال للقائمة. تُشكّل الانطباع الأول وتعكس هوية المكان البصرية.",
        icon: Coffee,
        badge: "عام",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/menu",
        titleAr: "قائمة المنتجات الكاملة",
        descAr: "صفحة التسوق الأساسية للعملاء — تعرض الفئات (مشروبات ساخنة، باردة، حلويات، سناندويشات...) مع إمكانية البحث عن منتج بالاسم. الضغط على أي منتج يفتح نافذة التخصيص (الحجم والإضافات) للإضافة المباشرة للسلة.",
        icon: Utensils,
        badge: "عام",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/menu-view",
        titleAr: "العرض البصري للقائمة (كتالوج)",
        descAr: "تصميم بديل للقائمة يشبه الكتالوج البصري مع عروض منزلقة وعرض تفصيلي لكل منتج — مناسب للعرض التقديمي أو الشاشات الكبيرة داخل الكافيه.",
        icon: Layers,
        badge: "عام",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/product/1",
        titleAr: "صفحة تفاصيل المنتج",
        descAr: "تعرض صورة المنتج، وصفه، مكوناته، سعره، خيارات التخصيص والأحجام المتاحة، وتقييمات العملاء السابقين. تُفتح تلقائياً عند الضغط على أي منتج في القائمة.",
        icon: Star,
        badge: "عام",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/order-status",
        titleAr: "شاشة حالة الطلبات المباشرة",
        descAr: "شاشة مصمّمة للعرض على شاشة خارجية في منطقة الانتظار — تُظهر الطلبات قيد التحضير والمكتملة وتُحدَّث فورياً في الوقت الفعلي دون الحاجة للتحديث اليدوي.",
        icon: ClipboardList,
        badge: "شاشة عامة",
        badgeColor: "bg-slate-100 text-slate-700",
        theme: "dark",
      },
      {
        path: "/customer-display",
        titleAr: "شاشة العملاء أمام الكاشير",
        descAr: "تُوصَل بشاشة ثانية أمام العميل في نقطة البيع — تعرض تفاصيل الطلب الحالي والمجموع والضريبة لحظةً بلحظة أثناء إضافة الموظف للمنتجات.",
        icon: Monitor,
        badge: "شاشة عامة",
        badgeColor: "bg-slate-100 text-slate-700",
        theme: "dark",
      },
      {
        path: "/table-menu/DEMO123",
        titleAr: "قائمة الطاولة عبر QR",
        descAr: "يمسح العميل رمز QR الموضوع على الطاولة فيُفتح له هذا الرابط تلقائياً — يظهر رقم طاولته ويمكنه الطلب منها مباشرة دون الحاجة لنادل.",
        icon: QrCode,
        badge: "QR",
        badgeColor: "bg-teal-100 text-teal-700",
        theme: "orange",
      },
      {
        path: "/table-checkout/1/5",
        titleAr: "إتمام طلب الطاولة",
        descAr: "صفحة إتمام الطلب المرتبطة بالطاولة — يُدخل العميل بيانات الدفع ويؤكد الطلب الذي يُرسَل مباشرةً للمطبخ. تُفتح تلقائياً بعد إضافة المنتجات من قائمة الطاولة.",
        icon: CreditCard,
        badge: "طاولة",
        badgeColor: "bg-teal-100 text-teal-700",
        theme: "orange",
      },
      {
        path: "/table-reservation",
        titleAr: "حجز الطاولات مسبقاً",
        descAr: "يختار العميل التاريخ والوقت وعدد الأشخاص ويُدخل اسمه ورقم هاتفه لحجز طاولة مسبقاً — دون الحاجة للاتصال بالكافيه. تُستخدم بدون تسجيل دخول.",
        icon: Calendar,
        badge: "عام",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/table-order-tracking/ORD001",
        titleAr: "تتبع طلب الطاولة",
        descAr: "بعد تأكيد طلب الطاولة تُفتح هذه الصفحة تلقائياً — تُظهر الحالة الحالية: «قيد التحضير»، «جاهز»، «تم التسليم» مع تحديث فوري.",
        icon: Navigation2,
        badge: "تتبع",
        badgeColor: "bg-blue-100 text-blue-700",
        theme: "orange",
      },
      {
        path: "/notifications",
        titleAr: "صفحة الإشعارات",
        descAr: "تعرض العروض الجديدة وتحديثات الطلبات ورسائل النظام — متاحة لجميع المستخدمين سواء سجّلوا دخولاً أم لا.",
        icon: Bell,
        badge: "عام",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/guide",
        titleAr: "دليل استخدام النظام",
        descAr: "شرح مصوّر لكل خطوات الطلب والدفع — مرجع تعليمي للعملاء الجدد. يشرح كيفية البحث في القائمة، إضافة منتجات، تحديد العنوان، واختيار طريقة الدفع.",
        icon: BookOpen,
        badge: "عام",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 2. صفحات تسجيل الدخول
  // ══════════════════════════════════════════════
  {
    id: "auth",
    titleAr: "بوابة العملاء — تسجيل الدخول والحساب",
    emoji: "🔑",
    color: "#2563eb",
    pages: [
      {
        path: "/auth",
        titleAr: "تسجيل الدخول / إنشاء حساب",
        descAr: "نقطة الدخول الرئيسية للعملاء — التحقق برقم الجوال وإنشاء حساب جديد أو تسجيل الدخول. تُطلب من العميل عند محاولة الوصول لأي صفحة محمية (السلة، الدفع، إلخ).",
        icon: User,
        badge: "دخول",
        badgeColor: "bg-blue-100 text-blue-700",
        theme: "sky",
      },
      {
        path: "/customer-login",
        titleAr: "دخول العملاء باسم المستخدم",
        descAr: "صفحة تسجيل دخول بديلة للعملاء الذين لديهم حسابات قديمة بالاسم وكلمة المرور — بديلٌ عن التحقق برقم الجوال.",
        icon: Lock,
        badge: "دخول",
        badgeColor: "bg-blue-100 text-blue-700",
        theme: "sky",
      },
      {
        path: "/forgot-password",
        titleAr: "استعادة كلمة المرور",
        descAr: "يُدخل العميل رقم جواله المسجّل لاستلام رابط أو رمز إعادة تعيين كلمة المرور.",
        icon: ShieldCheck,
        badge: "دخول",
        badgeColor: "bg-blue-100 text-blue-700",
        theme: "sky",
      },
      {
        path: "/reset-password",
        titleAr: "إعادة تعيين كلمة المرور",
        descAr: "يُدخل العميل كلمة المرور الجديدة بعد التحقق من هويته — تُفتح تلقائياً من رابط البريد الإلكتروني أو الرسالة النصية.",
        icon: RefreshCw,
        badge: "دخول",
        badgeColor: "bg-blue-100 text-blue-700",
        theme: "sky",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 3. صفحات العملاء المحمية
  // ══════════════════════════════════════════════
  {
    id: "customer-protected",
    titleAr: "بوابة العملاء — صفحات محمية (تتطلب تسجيل الدخول)",
    emoji: "🛒",
    color: "#ea580c",
    pages: [
      {
        path: "/cart",
        titleAr: "سلة التسوق",
        descAr: "تعرض جميع المنتجات المضافة مع الكميات والأسعار — يمكن تعديل الكميات أو حذف منتجات، مع عرض المجموع الكلي وزر الانتقال للدفع.",
        icon: ShoppingBag,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/delivery",
        titleAr: "اختيار طريقة الاستلام",
        descAr: "الخطوة الأولى في عملية الدفع — اختيار طريقة الاستلام: توصيل للمنزل أو استلام من الفرع، مع اختيار أقرب فرع للعميل.",
        icon: Truck,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/delivery/map",
        titleAr: "خريطة تحديد عنوان التوصيل",
        descAr: "تحديد موقع التوصيل تلقائياً أو بالضغط على الخريطة — تحسب رسوم التوصيل تلقائياً بناءً على المسافة من الفرع. تُفتح عند اختيار خدمة التوصيل.",
        icon: MapPin,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/checkout",
        titleAr: "صفحة الدفع الكاملة",
        descAr: "الخطوة الأخيرة — ملخص الطلب، اختيار طريقة الدفع (بطاقة، نقداً، Apple Pay، بطاقة الولاء)، استخدام النقاط كخصم، إدخال ملاحظات خاصة، وتأكيد الطلب النهائي.",
        icon: CreditCard,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/tracking",
        titleAr: "تتبع الطلب في الوقت الفعلي",
        descAr: "بعد تأكيد الدفع — مراحل الطلب: «مستلم» → «قيد التحضير» → «جاهز للاستلام» أو «في الطريق» مع معلومات السائق إذا كان طلب توصيل.",
        icon: Navigation2,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/payment-return",
        titleAr: "صفحة العودة بعد الدفع الإلكتروني",
        descAr: "تُفتح تلقائياً من بوابة الدفع بعد إتمام المعاملة — تُؤكد نجاح أو فشل عملية الدفع وتُوجّه العميل للخطوة التالية.",
        icon: Receipt,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/profile",
        titleAr: "الملف الشخصي للعميل",
        descAr: "البيانات الشخصية، رصيد النقاط، تاريخ الطلبات، وإعدادات الإشعارات — إدارة شاملة للحساب الشخصي.",
        icon: User,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/my-orders",
        titleAr: "سجل طلباتي السابقة",
        descAr: "سجل جميع الطلبات السابقة مع التفاصيل: التاريخ، المنتجات، المجموع، الحالة. يمكن إعادة طلب نفس الطلب بضغطة واحدة.",
        icon: ScrollText,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/my-card",
        titleAr: "بطاقة الولاء الرقمية",
        descAr: "رصيد النقاط الحالي ومستوى العضوية (برونزي، فضي، ذهبي، بلاتيني) مع تفاصيل المكافآت والمزايا لكل مستوى ورمز QR للاستخدام في نقطة البيع.",
        icon: Heart,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/copy-card",
        titleAr: "نسخة البطاقة القابلة للطباعة",
        descAr: "تصميم احترافي لبطاقة الولاء مع رمز QR الخاص بالعميل وإحصائيات النقاط والمكافآت — مناسبة للمشاركة أو الطباعة.",
        icon: Copy,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/card-customization",
        titleAr: "تخصيص مظهر بطاقة الولاء",
        descAr: "اختيار لون وتصميم بطاقة الولاء الرقمية حسب ذوق العميل — تغيير المظهر البصري للبطاقة.",
        icon: Palette,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/my-offers",
        titleAr: "العروض والكوبونات الخاصة بي",
        descAr: "الخصومات المتاحة، المدة الزمنية لكل عرض، وتطبيق العروض تلقائياً عند الطلب — اطلاع على العروض المخصصة لهذا الحساب.",
        icon: Tag,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/referrals",
        titleAr: "برنامج الإحالة",
        descAr: "مشاركة رمز الإحالة مع الأصدقاء وتتبع عدد الإحالات والنقاط المكتسبة — شرح آلية الحصول على نقاط إضافية بكل إحالة.",
        icon: Share2,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
      {
        path: "/my-reservations",
        titleAr: "حجوزاتي للطاولات",
        descAr: "عرض المواعيد القادمة وتاريخ الحجوزات السابقة — إمكانية إلغاء أو تعديل الحجز. إدارة شاملة لحجوزات الطاولات.",
        icon: Calendar,
        badge: "محمية",
        badgeColor: "bg-orange-100 text-orange-700",
        theme: "orange",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 4. بوابة الموظفين — عامة
  // ══════════════════════════════════════════════
  {
    id: "employee-public",
    titleAr: "بوابة الموظفين — صفحات عامة (بدون تسجيل دخول)",
    emoji: "👷",
    color: "#059669",
    pages: [
      {
        path: "/employee",
        titleAr: "شاشة ترحيب نظام الموظفين",
        descAr: "نقطة الدخول الرئيسية للموظفين — تُحمَّل بيانات الكافيه تلقائياً ثم تنتقل للبوابة المناسبة.",
        icon: PlayCircle,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/gateway",
        titleAr: "بوابة اختيار نوع المستخدم",
        descAr: "اختيار نوع المستخدم: موظف أو مدير — يوجّه كلاً منهما لصفحة تسجيل الدخول المناسبة. يفصل طريق الموظف عن المدير في بداية الدخول.",
        icon: ChevronRight,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/login",
        titleAr: "تسجيل دخول الموظف",
        descAr: "تسجيل دخول الموظف باسم المستخدم وكلمة المرور — للوصول لنظام الشيفتات والطلبات والأدوات المخصصة لدوره.",
        icon: Lock,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/forgot-password",
        titleAr: "استعادة كلمة مرور الموظف",
        descAr: "يُدخل الموظف اسم مستخدمه ثم يُنشئ كلمة مرور جديدة — إجراء استعادة آمن مرتبط بالمدير.",
        icon: ShieldCheck,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/activate",
        titleAr: "تفعيل حساب موظف جديد",
        descAr: "تُستخدم مرة واحدة فقط عند انضمام موظف جديد — يُدخل البيانات التي سجّلها المدير له وينشئ كلمة مرور خاصة به.",
        icon: UserCheck,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 5. بوابة الموظفين — محمية
  // ══════════════════════════════════════════════
  {
    id: "employee-protected",
    titleAr: "بوابة الموظفين — صفحات محمية (تتطلب تسجيل دخول كموظف)",
    emoji: "🏪",
    color: "#047857",
    pages: [
      {
        path: "/employee/home",
        titleAr: "الصفحة الرئيسية للموظف",
        descAr: "اختصارات سريعة للأقسام المتاحة حسب صلاحيات الموظف — لوحة تحكم سريعة تُوجّه الموظف لأدواته الأساسية.",
        icon: LayoutDashboard,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/dashboard",
        titleAr: "لوحة تحكم الموظف الكاملة",
        descAr: "إحصائيات الشيفت: عدد الطلبات، المبيعات، الطلبات المعلقة — مع روابط سريعة لجميع أدوات الموظف. المرجع الرئيسي طوال الشيفت.",
        icon: BarChart3,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/cashier",
        titleAr: "واجهة الكاشير",
        descAr: "استقبال الطلبات الواردة وعرض حالاتها — قبول أو رفض الطلبات وتحديث حالتها. المسؤول الرئيسي عن استلام الطلبات وتأكيدها.",
        icon: ClipboardCheck,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/pos",
        titleAr: "نقطة البيع (POS)",
        descAr: "إنشاء طلبات جديدة يدوياً للعملاء الحاضرين داخل الكافيه — إضافة منتجات، تعديل الكميات، تطبيق خصومات، طباعة الإيصال، واختيار طريقة الدفع.",
        icon: CreditCard,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/kitchen",
        titleAr: "شاشة المطبخ (KDS)",
        descAr: "تُعلَّق على شاشة في المطبخ — الطلبات الجديدة بالترتيب مع الوقت المستغرق، والضغط على طلب يُحدّث حالته لـ«جاهز»، مع تنبيه صوتي عند وصول طلب جديد.",
        icon: ChefHat,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/orders",
        titleAr: "قائمة جميع الطلبات",
        descAr: "قيد التحضير، مكتملة، ملغاة — تصفية حسب الحالة أو التاريخ مع عرض تفاصيل كل طلب. متابعة وإدارة الطلبات اليومية.",
        icon: ClipboardList,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/orders-display",
        titleAr: "شاشة الطلبات الجاهزة",
        descAr: "تُعلَّق على شاشة في منطقة الانتظار — تعرض أرقام الطلبات الجاهزة للاستلام لإبلاغ العملاء بدون الحاجة لمنادي.",
        icon: Monitor,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/tables",
        titleAr: "إدارة طاولات الكافيه",
        descAr: "خريطة الطاولات (متاحة، مشغولة، محجوزة) — تعيين طاولة لعميل وفتح طلب عليها. إدارة الجلوس وتوزيع الطاولات على العملاء.",
        icon: Tablet,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/table-orders",
        titleAr: "طلبات الطاولات النشطة",
        descAr: "طلبات عملاء الجلوس داخل الكافيه — إضافة منتجات لطلب طاولة مفتوح، إغلاق الطلب، وإصدار الفاتورة.",
        icon: ScrollText,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/reservations",
        titleAr: "إدارة الحجوزات",
        descAr: "قبول أو إلغاء الحجوزات المسبقة وتأكيد الحجز عند وصول العميل — استقبال وتنظيم الحجوزات من جانب الكاشير.",
        icon: Calendar,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/loyalty",
        titleAr: "نظام الولاء للموظف",
        descAr: "البحث عن بطاقة ولاء عميل برقم الجوال أو مسح رمز QR — إضافة نقاط بعد كل عملية شراء، واستبدالها كخصم على الطلب.",
        icon: Heart,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/shifts",
        titleAr: "إدارة الشيفتات",
        descAr: "تسجيل بداية ونهاية الشيفت وعرض ساعات العمل المسجّلة — يُسجّل الموظف دخوله وخروجه يومياً.",
        icon: Clock,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/attendance",
        titleAr: "سجل الحضور الشخصي",
        descAr: "تاريخ الحضور والغياب والتأخر — يراجع الموظف سجل حضوره الشخصي ويتحقق من ساعات عمله.",
        icon: FileText,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/leave-request",
        titleAr: "طلب إجازة رسمي",
        descAr: "تحديد نوع الإجازة (سنوية، مرضية، طارئة)، تاريخ البداية والنهاية، والسبب — متابعة حالة الطلب: معلق، موافق، مرفوض.",
        icon: Archive,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/availability",
        titleAr: "جدول توافر الموظف",
        descAr: "تحديد الأيام والأوقات المفضّلة للعمل — يُساعد المدير في جدولة المناوبات بناءً على توافر الموظفين.",
        icon: Calendar,
        badge: "موظف",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/employee/menu-management",
        titleAr: "إدارة قائمة المنتجات",
        descAr: "للمدير والمسؤول فقط — إضافة منتجات جديدة، تعديل الأسعار، رفع الصور، تفعيل أو إيقاف أي منتج مؤقتاً.",
        icon: Utensils,
        badge: "مشرف",
        badgeColor: "bg-amber-100 text-amber-700",
        theme: "green",
      },
      {
        path: "/employee/ingredients",
        titleAr: "إدارة المكونات والخامات",
        descAr: "للمدير والمسؤول فقط — رصيد المكونات المتوفرة وتحديثها. مراقبة المخزون من خلال الموظف المسؤول.",
        icon: FlaskConical,
        badge: "مشرف",
        badgeColor: "bg-amber-100 text-amber-700",
        theme: "green",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 6. بوابة المديرين — عامة
  // ══════════════════════════════════════════════
  {
    id: "manager-public",
    titleAr: "بوابة المديرين — الدخول",
    emoji: "👔",
    color: "#7c3aed",
    pages: [
      {
        path: "/manager",
        titleAr: "تسجيل دخول المدير",
        descAr: "نقطة الدخول الرئيسية للمديرين وأصحاب المطاعم — بصلاحيات أعلى من الموظف تشمل المخزون والمحاسبة والموظفين والتقارير.",
        icon: Lock,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/manager/forgot-password",
        titleAr: "استعادة كلمة مرور المدير",
        descAr: "إجراء آمن لاستعادة كلمة مرور حساب المدير عند النسيان.",
        icon: ShieldCheck,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 7. لوحات تحكم المديرين
  // ══════════════════════════════════════════════
  {
    id: "manager-dashboards",
    titleAr: "المديرون — لوحات التحكم والإحصائيات",
    emoji: "📊",
    color: "#6d28d9",
    pages: [
      {
        path: "/manager/dashboard",
        titleAr: "لوحة التحكم الرئيسية للمدير",
        descAr: "إجمالي المبيعات اليومية والأسبوعية والشهرية، عدد الطلبات، أكثر المنتجات مبيعاً، تنبيهات المخزون المنخفض، والطلبات المعلقة — المرجع اليومي للمدير.",
        icon: LayoutDashboard,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/executive",
        titleAr: "لوحة التحكم التنفيذية",
        descAr: "للمالك والمسؤول فقط — مؤشرات الأداء الرئيسية على مستوى جميع الفروع، رسوم بيانية للمبيعات والنمو. رؤية سريعة وشاملة لصاحب العمل.",
        icon: TrendingUp,
        badge: "مالك",
        badgeColor: "bg-amber-100 text-amber-700",
        theme: "violet",
      },
      {
        path: "/owner/dashboard",
        titleAr: "لوحة تحكم صاحب المطعم",
        descAr: "للمالك والمسؤول فقط — إدارة الاشتراكات، الفروع، والموظفين على مستوى المؤسسة، مع تقارير مالية تفصيلية.",
        icon: Building2,
        badge: "مالك",
        badgeColor: "bg-amber-100 text-amber-700",
        theme: "violet",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 8. إدارة الموظفين والحضور
  // ══════════════════════════════════════════════
  {
    id: "manager-hr",
    titleAr: "المديرون — إدارة الموظفين والرواتب",
    emoji: "👥",
    color: "#4f46e5",
    pages: [
      {
        path: "/manager/employees",
        titleAr: "قائمة جميع الموظفين",
        descAr: "إضافة موظف جديد، تعديل بياناته، تعيين دوره (كاشير، مطبخ، مدير)، تفعيل أو تجميد الحساب، وتعيين الفرع والراتب — إدارة كاملة لفريق العمل.",
        icon: Users,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/manager/attendance",
        titleAr: "تقارير الحضور والانصراف",
        descAr: "تقارير الحضور والانصراف لجميع الموظفين — تصفية حسب الموظف أو الفترة الزمنية مع تصدير التقارير. متابعة الحضور وحساب ساعات العمل.",
        icon: ClipboardCheck,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/manager/shifts",
        titleAr: "إدارة جداول المناوبات",
        descAr: "تعيين الموظفين للشيفتات ومتابعة الشيفتات المفتوحة والمغلقة — تنظيم جداول العمل الأسبوعية لجميع الموظفين.",
        icon: Clock,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/manager/payroll",
        titleAr: "إدارة الرواتب",
        descAr: "حساب الراتب بناءً على ساعات العمل والحضور وسجل صرف الرواتب — إعداد ودفع رواتب الموظفين شهرياً.",
        icon: Banknote,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 9. إدارة المخزون
  // ══════════════════════════════════════════════
  {
    id: "manager-inventory",
    titleAr: "المديرون — إدارة المخزون والمواد",
    emoji: "📦",
    color: "#0369a1",
    pages: [
      {
        path: "/manager/inventory/smart",
        titleAr: "لوحة المخزون الذكية",
        descAr: "نظرة عامة على جميع المواد والكميات مع تنبيهات الكميات المنخفضة — المرجع السريع لمستوى المخزون والمواد الأقرب للنفاد.",
        icon: Database,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/inventory/raw-items",
        titleAr: "إدارة المواد الخام",
        descAr: "إضافة مادة جديدة وتحديد وحدة القياس وسعر التكلفة — تعريف جميع المكونات المستخدمة في وصفات المنتجات.",
        icon: FlaskConical,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/inventory/suppliers",
        titleAr: "إدارة الموردين (من المخزون)",
        descAr: "بيانات المورد، المنتجات التي يوردها، أسعار الشراء — تنظيم علاقات الموردين وأسعارهم المرتبطة بالمخزون.",
        icon: Truck,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/inventory/purchases",
        titleAr: "سجل مشتريات المخزون",
        descAr: "تسجيل فاتورة شراء جديدة من مورد وتحديث الكميات تلقائياً بعد كل شراء — توثيق كامل لكل عملية شراء للمخزون.",
        icon: Receipt,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/inventory/recipes",
        titleAr: "ربط المنتجات بالوصفات",
        descAr: "تحديد الكميات المستهلكة من كل مكون لكل منتج — خصم المخزون تلقائياً عند بيع المنتج. تحكم دقيق في تكلفة الإنتاج.",
        icon: Layers2,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/inventory/stock",
        titleAr: "الرصيد الحالي للمخزون",
        descAr: "عرض الرصيد الفعلي لكل مادة خام مع إمكانية التعديل اليدوي (جرد) — مراجعة المخزون الفعلي وتصحيح الفوارق.",
        icon: Boxes,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/inventory/alerts",
        titleAr: "تنبيهات المخزون المنخفض",
        descAr: "قائمة بالمواد التي وصلت لحد التنبيه — اتخاذ قرار الشراء قبل نفاد المواد وتعطّل الإنتاج.",
        icon: AlertTriangle,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/inventory/movements",
        titleAr: "سجل حركات المخزون",
        descAr: "تتبع كل استهلاك أو إضافة مع الوقت والسبب — مراجعة دقيقة لكل ما دخل وخرج من المستودع ومنع الهدر.",
        icon: TrendingUp,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/inventory/stock-organization",
        titleAr: "تنظيم وتصنيف المخزون",
        descAr: "إدارة مواقع التخزين وتنظيم الرفوف — تنظيم فيزيائي للمخزون داخل المستودع وتصنيف المواد.",
        icon: BoxSelect,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/unified-inventory",
        titleAr: "لوحة موحدة للمخزون والوصفات",
        descAr: "ربط المكونات بالمنتجات في واجهة واحدة — إدارة المخزون والوصفات من مكان واحد بدون التنقل بين صفحات.",
        icon: Layers,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/os-inventory",
        titleAr: "نظام إدارة المخزون المتقدم",
        descAr: "تقارير شاملة وتحليلات استهلاك متقدمة — للمطاعم الكبيرة التي تحتاج تحكماً أعمق في مخزونها ووصفاتها.",
        icon: Database,
        badge: "متقدم",
        badgeColor: "bg-indigo-100 text-indigo-700",
        theme: "sky",
      },
      {
        path: "/manager/warehouse",
        titleAr: "إدارة المستودع",
        descAr: "تتبع الكميات في مستودعات متعددة — للكافيهات التي لديها مستودع مركزي منفصل عن الفرع.",
        icon: Warehouse,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/suppliers",
        titleAr: "إدارة الموردين (المستقلة)",
        descAr: "التواصل والتفاوض وطلبات التوريد — متابعة علاقات الموردين وتاريخ التعامل وأسعار التوريد.",
        icon: Package,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 10. المحاسبة والمالية
  // ══════════════════════════════════════════════
  {
    id: "manager-finance",
    titleAr: "المديرون — المحاسبة والمالية",
    emoji: "💰",
    color: "#065f46",
    pages: [
      {
        path: "/manager/accounting",
        titleAr: "لوحة المحاسبة الرئيسية",
        descAr: "الإيرادات والمصاريف والأرباح اليومية والشهرية — تقارير مالية قابلة للتصدير. متابعة الوضع المالي الكامل للكافيه.",
        icon: Banknote,
        badge: "مدير",
        badgeColor: "bg-emerald-100 text-emerald-700",
        theme: "green",
      },
      {
        path: "/manager/accounting/smart",
        titleAr: "المحاسبة الذكية بالذكاء الاصطناعي",
        descAr: "تحليل أنماط المبيعات وتوقع الإيرادات باستخدام الذكاء الاصطناعي — رؤية مستقبلية للأداء المالي واتخاذ قرارات استباقية.",
        icon: Zap,
        badge: "ذكاء اصطناعي",
        badgeColor: "bg-purple-100 text-purple-700",
        theme: "green",
      },
      {
        path: "/manager/zatca",
        titleAr: "فواتير ZATCA الإلكترونية",
        descAr: "إنشاء فواتير ضريبية متوافقة مع اشتراطات هيئة الزكاة والضريبة والجمارك — تصدير بصيغة XML للرفع على منصة فاتورة. للامتثال التام في المملكة العربية السعودية.",
        icon: BadgeCheck,
        badge: "ZATCA",
        badgeColor: "bg-green-100 text-green-700",
        theme: "green",
      },
      {
        path: "/erp/accounting",
        titleAr: "نظام المحاسبة المتكامل (ERP)",
        descAr: "دفتر اليومية، الحسابات، الميزانية العمومية — محاسبة احترافية على مستوى الشركات لمن يحتاج نظاماً محاسبياً متكاملاً.",
        icon: ScrollText,
        badge: "ERP",
        badgeColor: "bg-indigo-100 text-indigo-700",
        theme: "green",
      },
      {
        path: "/manager/os-accounting",
        titleAr: "نظام المحاسبة المتكامل المتقدم",
        descAr: "محاسبة على مستوى المؤسسة مع تكامل المخزون — للمطاعم والمتاجر الكبيرة التي تحتاج تكاملاً عميقاً بين المالية والمخزون.",
        icon: PieChart,
        badge: "متقدم",
        badgeColor: "bg-indigo-100 text-indigo-700",
        theme: "green",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 11. التوصيل والطاولات
  // ══════════════════════════════════════════════
  {
    id: "manager-delivery",
    titleAr: "المديرون — إدارة التوصيل والطاولات",
    emoji: "🚗",
    color: "#0284c7",
    pages: [
      {
        path: "/manager/tables",
        titleAr: "إدارة طاولات الكافيه (المدير)",
        descAr: "رسم مخطط الطاولات وتحديد أحجامها وأماكنها — إعداد خريطة الطاولات وإدارة الحجوزات من منظور المدير.",
        icon: Tablet,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/delivery",
        titleAr: "إدارة طلبات التوصيل",
        descAr: "تعيين السائقين للطلبات وتتبع حالة كل طلب توصيل — إدارة عمليات التوصيل اليومية وتوزيع العمل على السائقين.",
        icon: Truck,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/drivers",
        titleAr: "إدارة السائقين",
        descAr: "بيانات كل سائق، المناطق المعيّنة له، الطلبات المُسلّمة — إدارة فريق التوصيل وتتبع أدائهم.",
        icon: Truck,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/manager/delivery-services",
        titleAr: "خدمات التوصيل الخارجية",
        descAr: "مراقبة حالة الاتصال بمنصات التوصيل الخارجية — التحقق من تكامل التوصيل مع المنصات الشريكة.",
        icon: Globe,
        badge: "مدير",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 12. التقارير والتحليلات
  // ══════════════════════════════════════════════
  {
    id: "manager-analytics",
    titleAr: "المديرون — التقارير والتحليلات",
    emoji: "📈",
    color: "#7c3aed",
    pages: [
      {
        path: "/manager/analytics",
        titleAr: "التحليلات المتقدمة",
        descAr: "تقارير المبيعات والعملاء والمنتجات بمؤشرات بيانية تفاعلية — اتخاذ قرارات استراتيجية مبنية على البيانات الفعلية.",
        icon: BarChart3,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/manager/unified-reports",
        titleAr: "تقارير موحدة شاملة",
        descAr: "تجمع المبيعات والمخزون والموظفين في تقرير واحد — تصدير بصيغ Excel وPDF. مناسبة لاجتماعات الإدارة والمراجعات الدورية.",
        icon: ScrollText,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/manager/bi-analytics",
        titleAr: "تحليلات ذكاء الأعمال (BI)",
        descAr: "رسوم بيانية تفاعلية، مقارنات فترات، توقعات — تحليل عميق لبيانات الكافيه لاتخاذ قرارات مدروسة ومبنية على بيانات.",
        icon: LineChart,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/manager/reviews",
        titleAr: "إدارة مراجعات العملاء",
        descAr: "عرض التقييمات وتصفيتها حسب المنتج أو النجوم مع إمكانية الرد على التعليقات — متابعة رأي العملاء وتحسين الخدمة.",
        icon: MessageSquare,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/reports",
        titleAr: "تقارير عامة",
        descAr: "للمدير والمالك والمسؤول — وصول سريع للتقارير الأساسية: مبيعات، مخزون، موظفين.",
        icon: FileText,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/stock-movements",
        titleAr: "تقرير حركات المخزون التفصيلي",
        descAr: "مراجعة دقيقة لكل ما دخل وخرج من المستودع — تقرير مفصّل بكل حركة مخزون مع الوقت والسبب والكمية.",
        icon: TrendingUp,
        badge: "مدير",
        badgeColor: "bg-violet-100 text-violet-700",
        theme: "violet",
      },
      {
        path: "/inventory/dashboard",
        titleAr: "لوحة تحكم المخزون المجمعة",
        descAr: "نظرة شاملة على المخزون عبر الفروع للمسؤولين — لوحة مجمّعة تعرض مخزون جميع الفروع في مكان واحد.",
        icon: Boxes,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "violet",
      },
      {
        path: "/accounting/dashboard",
        titleAr: "لوحة تحكم المحاسبة المجمعة",
        descAr: "ملخص مالي شامل عبر الفروع للمسؤولين — تقارير مالية مجمّعة من جميع الفروع في لوحة واحدة.",
        icon: PieChart,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "violet",
      },
      {
        path: "/recipes/management",
        titleAr: "إدارة الوصفات المركزية",
        descAr: "للمسؤولين — إضافة وتعديل وصفات المنتجات مركزياً على مستوى جميع الفروع.",
        icon: FlaskConical,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "violet",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 13. الولاء وبطاقات الهدايا
  // ══════════════════════════════════════════════
  {
    id: "manager-loyalty",
    titleAr: "المديرون — الولاء والعروض",
    emoji: "🎁",
    color: "#be185d",
    pages: [
      {
        path: "/manager/loyalty",
        titleAr: "إدارة برنامج الولاء",
        descAr: "إعداد عدد النقاط لكل ريال، قيمة النقطة، مستويات العضوية وشروط الترقي — تصميم برنامج الولاء الكامل وإعداد قواعده.",
        icon: Heart,
        badge: "مدير",
        badgeColor: "bg-pink-100 text-pink-700",
        theme: "violet",
      },
      {
        path: "/manager/gift-cards",
        titleAr: "إدارة بطاقات الهدايا",
        descAr: "إنشاء بطاقات هدايا بقيم محددة وتتبع استخدام البطاقات والأرصدة — بيع وإدارة بطاقات الهدايا للعملاء.",
        icon: Gift,
        badge: "مدير",
        badgeColor: "bg-pink-100 text-pink-700",
        theme: "violet",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 14. الأنظمة المتقدمة
  // ══════════════════════════════════════════════
  {
    id: "manager-advanced",
    titleAr: "المديرون — أنظمة متقدمة وتكاملات",
    emoji: "⚙️",
    color: "#374151",
    pages: [
      {
        path: "/manager/os-roles",
        titleAr: "إدارة الأدوار والصلاحيات",
        descAr: "للمالك والمسؤول فقط — تحديد ما يمكن لكل دور فعله في النظام. التحكم الكامل في صلاحيات الوصول لكل وظيفة.",
        icon: ShieldCheck,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "slate",
      },
      {
        path: "/manager/os-stock",
        titleAr: "إدارة المخزون المتقدمة",
        descAr: "تحكم دقيق وشامل في المخزون — نظام متقدم للمطاعم الكبيرة التي تحتاج مستوى أعمق من إدارة المواد والكميات.",
        icon: Database,
        badge: "متقدم",
        badgeColor: "bg-slate-100 text-slate-700",
        theme: "slate",
      },
      {
        path: "/manager/os-recipes",
        titleAr: "إدارة الوصفات المتقدمة",
        descAr: "ربط دقيق بين الوصفات والمخزون والتكاليف — حساب تكلفة الإنتاج الفعلية لكل منتج بناءً على مكوناته.",
        icon: FlaskConical,
        badge: "متقدم",
        badgeColor: "bg-slate-100 text-slate-700",
        theme: "slate",
      },
      {
        path: "/manager/integrations",
        titleAr: "التكاملات الخارجية",
        descAr: "ربط النظام بخدمات خارجية (توصيل، دفع، تسويق) — توسيع قدرات النظام بربطه بمنصات خارجية وتكاملات API.",
        icon: Wrench,
        badge: "مسؤول",
        badgeColor: "bg-slate-100 text-slate-700",
        theme: "slate",
      },
      {
        path: "/manager/support",
        titleAr: "نظام الدعم الفني",
        descAr: "تذاكر الدعم والمحادثات مع فريق QIROX — طلب المساعدة التقنية مع تتبع حالة التذاكر والردود.",
        icon: MessageSquare,
        badge: "مدير",
        badgeColor: "bg-slate-100 text-slate-700",
        theme: "slate",
      },
      {
        path: "/manager/guide",
        titleAr: "دليل استخدام النظام للمديرين",
        descAr: "شرح تفصيلي لكل وظيفة في النظام — مرجع تعليمي لاستيعاب كامل إمكانيات منصة إدارة الكافيه.",
        icon: BookOpen,
        badge: "مدير",
        badgeColor: "bg-slate-100 text-slate-700",
        theme: "slate",
      },
      {
        path: "/manager/ingredients-recipes",
        titleAr: "المكونات والوصفات المدمجة",
        descAr: "إدارة المكونات وربطها بالوصفات في واجهة واحدة — ضبط دقيق للمكونات والوصفات وتكاليف الإنتاج.",
        icon: Layers2,
        badge: "مدير",
        badgeColor: "bg-slate-100 text-slate-700",
        theme: "slate",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 15. بوابة السائقين
  // ══════════════════════════════════════════════
  {
    id: "driver",
    titleAr: "بوابة السائقين",
    emoji: "🚗",
    color: "#0369a1",
    pages: [
      {
        path: "/driver/login",
        titleAr: "تسجيل دخول السائق",
        descAr: "نقطة الدخول الخاصة بسائقي التوصيل — يُدخل السائق بياناته للوصول لطلباته المُعيّنة والخرائط.",
        icon: Lock,
        badge: "سائق",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/driver/portal",
        titleAr: "لوحة تحكم السائق",
        descAr: "الطلبات المعيّنة للسائق مع العناوين والخرائط — تحديث حالة التوصيل (في الطريق، تم التسليم). أداة العمل اليومية لسائق التوصيل.",
        icon: Truck,
        badge: "سائق",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
      {
        path: "/delivery/track/ORD001",
        titleAr: "تتبع التوصيل للعميل",
        descAr: "موقع السائق على الخريطة في الوقت الفعلي مع الوقت التقديري للوصول — يُرسَل رابط التتبع للعميل بعد خروج السائق.",
        icon: MapPin,
        badge: "عام",
        badgeColor: "bg-sky-100 text-sky-700",
        theme: "sky",
      },
    ],
  },

  // ══════════════════════════════════════════════
  // 16. بوابة المسؤولين
  // ══════════════════════════════════════════════
  {
    id: "admin",
    titleAr: "بوابة المسؤولين (Admin)",
    emoji: "🔧",
    color: "#dc2626",
    pages: [
      {
        path: "/admin/dashboard",
        titleAr: "لوحة تحكم المسؤول",
        descAr: "إحصائيات شاملة، ملخص المبيعات، والأداء العام للنظام — نظرة شاملة للمسؤول على كامل النظام بجميع فروعه.",
        icon: LayoutDashboard,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "red",
      },
      {
        path: "/admin/employees",
        titleAr: "إدارة الموظفين (المسؤول)",
        descAr: "إدارة جميع الموظفين على مستوى المؤسسة — إدارة مركزية للموارد البشرية عبر جميع الفروع.",
        icon: Users,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "red",
      },
      {
        path: "/admin/reports",
        titleAr: "تقارير المسؤول الشاملة",
        descAr: "مبيعات وأداء وإحصائيات على أعلى مستوى — تقارير شاملة تغطي جميع الفروع والموظفين.",
        icon: BarChart3,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "red",
      },
      {
        path: "/admin/settings",
        titleAr: "إعدادات النظام الكاملة",
        descAr: "بيانات الكافيه، الشعار، ألوان التطبيق، إعدادات الدفع (Geidea)، إعدادات ZATCA، بيانات الضريبة، وضع الصيانة، البريد الإلكتروني والإشعارات — تكوين شامل للنظام.",
        icon: Settings,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "red",
      },
      {
        path: "/admin/branches",
        titleAr: "إدارة الفروع",
        descAr: "إضافة فرع جديد، تحديد موقعه، ربط الموظفين به — إدارة نظام متعدد الفروع مع تحديد إعدادات كل فرع.",
        icon: Building2,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "red",
      },
      {
        path: "/admin/email",
        titleAr: "إدارة قوالب البريد الإلكتروني",
        descAr: "تخصيص رسائل التأكيد والترحيب والتذكير — إعداد الرسائل الآلية التي تُرسَل للعملاء بعد كل عملية.",
        icon: Mail,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "red",
      },
      {
        path: "/admin/notifications",
        titleAr: "إرسال إشعارات جماعية",
        descAr: "إرسال إشعارات جماعية للعملاء — إشعارات فورية (Push) أو برسالة نصية أو بريد إلكتروني لجميع المستخدمين أو مجموعات مستهدفة.",
        icon: Bell,
        badge: "مسؤول",
        badgeColor: "bg-red-100 text-red-700",
        theme: "red",
      },
    ],
  },
];
