// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ecosystem/HumanTech.tsx": () => import("../components/mockups/ecosystem/HumanTech.tsx"),
  "./components/mockups/ecosystem/LuxurySaudi.tsx": () => import("../components/mockups/ecosystem/LuxurySaudi.tsx"),
  "./components/mockups/ecosystem/PlatformGrid.tsx": () => import("../components/mockups/ecosystem/PlatformGrid.tsx"),
  "./components/mockups/ecosystem/QiroxBento.tsx": () => import("../components/mockups/ecosystem/QiroxBento.tsx"),
  "./components/mockups/ecosystem/SectorCards.tsx": () => import("../components/mockups/ecosystem/SectorCards.tsx"),
  "./components/mockups/install-flow/IOSInstallGuide.tsx": () => import("../components/mockups/install-flow/IOSInstallGuide.tsx"),
  "./components/mockups/install-flow/IPhoneApp.tsx": () => import("../components/mockups/install-flow/IPhoneApp.tsx"),
  "./components/mockups/install-flow/PWAInstallPopup.tsx": () => import("../components/mockups/install-flow/PWAInstallPopup.tsx"),
  "./components/mockups/sales-dashboard/EmployeeCard.tsx": () => import("../components/mockups/sales-dashboard/EmployeeCard.tsx"),
  "./components/mockups/sales-dashboard/LeadCard.tsx": () => import("../components/mockups/sales-dashboard/LeadCard.tsx"),
  "./components/mockups/sales-dashboard/SalesDashboard.tsx": () => import("../components/mockups/sales-dashboard/SalesDashboard.tsx"),
  "./components/mockups/hero-visual/Current.tsx": () => import("../components/mockups/hero-visual/Current.tsx"),
  "./components/mockups/hero-visual/Larger.tsx": () => import("../components/mockups/hero-visual/Larger.tsx")
};
