// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sales-dashboard/EmployeeCard.tsx": () => import("../components/mockups/sales-dashboard/EmployeeCard.tsx"),
  "./components/mockups/sales-dashboard/LeadCard.tsx": () => import("../components/mockups/sales-dashboard/LeadCard.tsx"),
  "./components/mockups/sales-dashboard/SalesDashboard.tsx": () => import("../components/mockups/sales-dashboard/SalesDashboard.tsx")
};
