import mongoose from "mongoose";
import { roles } from "@shared/schema";
import { transform } from "./utils";

const userSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  password: { type: String, default: "" },
  email: { type: String, required: true, unique: true },
  googleId: { type: String, sparse: true, index: true },
  googleAvatarUrl: String,
  githubId: { type: String, sparse: true, index: true },
  githubAvatarUrl: String,
  appleId: { type: String, sparse: true, index: true },
  role: { type: String, enum: [...roles], default: "client", required: true },
  employeeCode: { type: String, unique: true, sparse: true, index: true },
  fullName: { type: String, required: true },
  phone: String,
  country: String,
  businessType: String,
  address: { type: String, default: "" },
  city: { type: String, default: "" },
  taxNumber: { type: String, default: "" },
  organizationName: { type: String, default: "" },
  commercialRegistration: { type: String, default: "" },
  nationalAddress: { type: String, default: "" },
  emailVerified: { type: Boolean, default: false },
  whatsappNumber: String,
  logoUrl: String,
  avatarUrl: String,
  subscriptionSegmentId: String,
  subscriptionSegmentNameAr: String,
  subscriptionPeriod: { type: String, enum: ["monthly", "6months", "annual", "renewal"], default: null },
  subscriptionStartDate: Date,
  subscriptionExpiresAt: Date,
  subscriptionStatus: { type: String, enum: ["active", "expired", "none", "suspended"], default: "none" },
  renewalReminderSentAt: { type: Date, default: null },
  isProjectLive: { type: Boolean, default: false },
  projectLiveAt: { type: Date, default: null },
  walletCardNumber: { type: String, unique: true, sparse: true, select: false },
  walletPin: { type: String, select: false },
  walletCardActive: { type: Boolean, default: false },
  walletBalance: { type: Number, default: 0, min: 0 },
  jobTitle: { type: String, default: "" },
  workEmail: { type: String, default: "" },
  bio: { type: String, default: "" },
  profilePhotoUrl: { type: String, default: "" },
  additionalRoles: { type: [String], default: [] },
  trustedIp: String,
  trustedUntil: Date,
  quickPin: { type: String, select: false },
  quickPinSetAt: { type: Date, select: false },
  avatarConfig: { type: String, default: "" },
  instagram: { type: String, default: "" },
  twitter: { type: String, default: "" },
  linkedin: { type: String, default: "" },
  snapchat: { type: String, default: "" },
  tiktok: { type: String, default: "" },
  youtube: { type: String, default: "" },
  linktree: { type: String, default: "" },
  totpSecret: { type: String, select: false },
  totpEnabled: { type: Boolean, default: false },
  emailOtpEnabled: { type: Boolean, default: false },
  recoveryPassphrase: { type: String, select: false },
  recoveryPassphraseEnabled: { type: Boolean, default: false },
  pushApprovalEnabled: { type: Boolean, default: false },
  phoneVerified: { type: Boolean, default: false },
  referralCode: { type: String, sparse: true, index: true },
  referredBy: { type: String, default: null },
  referralCreditsEarned: { type: Number, default: 0 },
  qrLoginToken: { type: String, sparse: true, index: true },
  qrLoginTokenCreatedAt: { type: Date, default: null },
  qrLoginTokenExpiresAt: { type: Date, default: null, index: true },
  qrLoginTokenRotatedAt: { type: Date, default: null },
  qrLoginTokenLastUsedAt: { type: Date, default: null },
  assignedSalesId: { type: String, default: null },
  assignedSalesName: { type: String, default: null },
  assignedSalesUsername: { type: String, default: null },
  githubDeployToken: { type: String, default: null, select: false },
  allowedPages: { type: [String], default: null },
}, { timestamps: true });

userSchema.index({ role: 1 });
userSchema.index({ role: 1, createdAt: -1 });
userSchema.index({ createdAt: -1 });
userSchema.set('toJSON', { transform });
userSchema.set('toObject', { transform });

export const UserModel = mongoose.models.User || mongoose.model("User", userSchema);
