-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgO+B47wTjrHFpd4pk
HAOcjIFhIU7HfIoSSz+7DRqpgRugCgYIKoZIzj0DAQehRANCAASwxl0MhUIvf86k
yTYGwyjZPePdcSf+fJYoLBAEf0yX181Ucc20wVVwHZl9ehpfheCKIPZa1Jye+HUU
5ash0jAQ
-----END PRIVATE KEY-----